<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Deterministic>true</Deterministic>
    <Authors>ClearC contributors</Authors>
    <RepositoryUrl>https://github.com/dotnet9/ClearC</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/dotnet9/ClearC</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile Condition="'$(MSBuildProjectName)' != 'ClearC.Desktop'">true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
