<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PublishAot Condition="'$(RuntimeIdentifier)' == 'win-x64'">true</PublishAot>
    <PublishTrimmed Condition="'$(RuntimeIdentifier)' == 'win-x64'">true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="Roots.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClearC.Core\ClearC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClearC.Desktop.Tests" />
  </ItemGroup>
</Project>
