<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0-windows;net10.0</TargetFrameworks>
    <BuiltInComInteropSupport Condition="'$(TargetFramework)' == 'net10.0-windows'">true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <PublishAot Condition="'$(RuntimeIdentifier)' == 'win-x64' or '$(RuntimeIdentifier)' == 'win-x86'">true</PublishAot>
    <PublishTrimmed Condition="'$(RuntimeIdentifier)' != ''">true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="Roots.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="CodeWF.Log.Avalonia" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="Semi.Avalonia.DataGrid" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClearC.Core\ClearC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClearC.Desktop.Tests" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\..\logo.png" Link="Assets\logo.png" />
    <AvaloniaResource Include="..\..\logo.ico" Link="Assets\logo.ico" />
  </ItemGroup>
</Project>
